spring:
  datasource:
    url: jdbc:mysql://localhost:3306/try_trans??useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  type-aliases-package: com.shiw.enterpriseusercenter.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true