spring:
  datasource:
    url: jdbc:mysql://localhost:3306/try_trans?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    data-username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true

mybatis:
  type-aliases-package: com.shiw.enterpriseusercenter.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true