server:
  port: 8080
  servlet:
    context-path:

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active: dev
  application:
    name: usercenter
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
