server:
  port: 8081
  servlet:
    context-path:

eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka
spring:
  profiles:
    active: dev
  application:
    name: structrue
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8